[package]
name = "sdpe"
version = "0.1.0"
authors = ["Corentin BROSSUTTI"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
rrsa = { path = "../rrsa" }